// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* Some */[(function (obj) {
          return obj.id;
        })], /* None */0, /* () */0);

var httpLink = ApolloLinks.createHttpLink("http://localhost:3010/graphql", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var apolloClient = ReasonApollo.createApolloClient(inMemoryCache, httpLink, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var Client = ReasonApollo.CreateClient(/* module */[/* apolloClient */apolloClient]);

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.Client = Client;
/* inMemoryCache Not a pure module */
