// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function getActive(callback) {
  chrome.tabs.query({
        active: true
      }, (function (tabs) {
          console.log("tabs: ", tabs);
          return Curry._1(callback, Caml_array.caml_array_get(tabs, 0));
        }));
  return /* () */0;
}

var Tabs = /* module */[/* getActive */getActive];

exports.Tabs = Tabs;
/* No side effect */
