// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Printf = require("bs-platform/lib/js/printf.js");
var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ApolloLink = require("apollo-link");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");
var Config$ReactTemplate = require("./config.bs.js");

function logout() {
  return /* () */0;
}

var httpLink = ApolloLinks.createHttpLink(Curry._1(Printf.sprintf(/* Format */[
              /* String_literal */Block.__(11, [
                  "http://serve.onegraph.io:8082/dynamic?app_id=",
                  /* String */Block.__(2, [
                      /* No_padding */0,
                      /* End_of_format */0
                    ])
                ]),
              "http://serve.onegraph.io:8082/dynamic?app_id=%s"
            ]), Config$ReactTemplate.appId), /* None */0, /* None */0, /* None */0, /* Some */["include"], /* None */0, /* () */0);

function contextHandler() {
  return {
          headers: {
            show_beta_schema: "true"
          }
        };
}

var authLink = ApolloLinks.createContextLink(contextHandler);

function errorHandler(errorResponse) {
  var match = errorResponse.networkError;
  if (match) {
    match[0].statusCode === 401;
    return /* () */0;
  } else {
    return /* () */0;
  }
}

var errorLink = ApolloLinks.createErrorLink(errorHandler);

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* Some */[(function (obj) {
          if (obj.__typename === "Organization") {
            return obj.key;
          } else {
            return obj.id;
          }
        })], /* None */0, /* () */0);

var apolloClient = ReasonApollo.createApolloClient(inMemoryCache, ApolloLink.from(/* array */[
          authLink,
          errorLink,
          httpLink
        ]), /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var Instance = ReasonApollo.CreateClient(/* module */[/* apolloClient */apolloClient]);

exports.logout = logout;
exports.httpLink = httpLink;
exports.contextHandler = contextHandler;
exports.authLink = authLink;
exports.errorHandler = errorHandler;
exports.errorLink = errorLink;
exports.inMemoryCache = inMemoryCache;
exports.Instance = Instance;
/* httpLink Not a pure module */
