// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var _appId = "6c510423-45bc-4f46-af1b-54bc1676c10c";

var appId = "cd35c827-e257-4c47-bd7b-a53bf40263bc";

exports._appId = _appId;
exports.appId = appId;
/* No side effect */
