// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function s(prim) {
  return prim;
}

function $$default(value, option) {
  if (option) {
    return option[0];
  } else {
    return value;
  }
}

function bind(f, param) {
  if (param) {
    return Curry._1(f, param[0]);
  } else {
    return /* None */0;
  }
}

exports.s = s;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.bind = bind;
/* No side effect */
