// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


function s(prim) {
  return prim;
}

function $$default(value, option) {
  if (option) {
    return option[0];
  } else {
    return value;
  }
}

exports.s = s;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* No side effect */
